"""empty message

Revision ID: 4e4ecf936f24
Revises: 
Create Date: 2020-04-10 17:55:20.857364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e4ecf936f24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_gateway',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('params_hash', sa.JSON(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('endpoint_type', sa.String(length=30), nullable=True),
    sa.Column('request_status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('communication_gateway')
    # ### end Alembic commands ###
